### ISSUE TITLE
Base loses connection to top when battery low 

### ISSUE THREAD

**Issue by KUKARAF** [linux-surface/surface-dtx-daemon#15]
on my SB2 the base disconnects when the battery in the base is discharged and the top battery in the main device is charged. 
![image](https://github.com/linux-surface/surface-dtx-daemon/assets/24418303/51a789a8-3e40-46fc-a233-db078fd4ff71)

The error message instructs me to consult the lgos, but I am unable to find anything in /var/log.

**Comment by qzed** [comment]
If that happens again, can you post the dmesg log from around that time as well as the output of `journalctl -eu surface-dtx-daemon.service`?

**Comment by KUKARAF** [comment]
It seems to occur very sporadically. I will get back to you when it occurrs again

**Comment by KUKARAF** [comment]
Got it! 

```
[rafa@sb2 ~]$ journalctl -eu surface-dtx-daemon.service > dtx_log.log
[rafa@sb2 ~]$ cat dtx_log.log 
Sep 12 14:54:17 sb2 systemd[1]: Started surface-dtx-daemon.service - Surface Detachment System (DTX) Daemon.
Sep 12 14:54:17 sb2 surface-dtx-daemon[1070]:  INFO sdtxd: running...
Sep 14 16:04:32 sb2 surface-dtx-daemon[1070]: ERROR sdtxd::core: unexpected disconnect: latch is closed
[rafa@sb2 ~]$ 
````

**Comment by qzed** [comment]
What about dmesg log?

And can you try to clean your connectors to see if that might be the problem?

**Comment by KUKARAF** [comment]
It occurs when the battery drops around 30% and happened a few times when the laptop was not being touched, completely stationary on a table. I strongly doubt it's the connector, but it won't hurt to try.  

I will get the dmesg output too when it happens next.

**Comment by qzed** [comment]
Yeah. It's fairly unlikely to be a software issue as well. So I was thinking that if the connectors might not be clean and some voltage drops below a certain level, the connection might flake out. Not sure we really can do much if cleaning the connectors doesn't work apart from collecting as much info on it as possible.

**Comment by KUKARAF** [comment]
I got the dmesg output. It again happened at 33% in total when the base battery ran out and the top battery started taking over. 

Does this line perhaps have something to do with it? 

`[170991.666017] pci 0000:02:00.0: Unable to change power state from D3cold to D0, device inaccessible`

[sep26_12_17.log](https://github.com/linux-surface/surface-dtx-daemon/files/12726282/sep26_12_17.log)

**Comment by qzed** [comment]
Yeah, that line is related. More so the two preceding it:
```
[170991.665544] pcieport 0000:00:1c.4: Data Link Layer Link Active not set in 1000 msec
[170991.665618] pcieport 0000:00:1c.4: pciehp: Slot(4): Card not present
[170991.666017] pci 0000:02:00.0: Unable to change power state from D3cold to D0, device inaccessible
```
That's essentially the GPU in the base not responding.

And before that
```
[170986.192212] usb 1-1: USB disconnect, device number 2
[170986.192220] usb 1-1.1: USB disconnect, device number 4
[170986.195157] usb 1-1.3: USB disconnect, device number 11
[170986.389464] usb 2-1: USB disconnect, device number 2
[170986.389480] usb 2-1.1: USB disconnect, device number 3
```

So it's not just the EC that detects that the base is disconnected, the actual devices in the base (USB, PCIe GPU) also loose connection. It does look like the USB devices are reconnected after a couple of seconds. But the connection doesn't seem to be good because it's dropping them again. The PCIe connection to the GPU seems to come back as well, but way later.

Given that this happens across EC, USB, and PCIe connections (which are pretty much all connections to the base), I'm pretty sure that it has to be some hardware fault or maybe a bad/dirty connector. So I'm afraid I don't think there's anything we can do about this from the kernel side.

**Comment by KUKARAF** [comment]
So if I understand this correctly, the pins responsible for transferring power to the base are damaged/dirty/corroded and therefore the base loses power?  
The connects themselves look pretty clean to me and this computer is glued together, and troubleshooting this with a multimeter would be a pain.


I will give the pins the good'ol alcohol, toothbrush and eraser treatment again, see if I am just not seeing something. 
I will also try out different systems just to be certain before I put in all this work of disassembling this device. 

Let's close this ticket for now and assume that you are right. If I find out more details, I'll let you know.

**Comment by qzed** [comment]
I guess it could also be possible that some flex-cable in the hinge mechanism has gone bad. Doesn't necessarily have to be the contacts themselves, but it looks like some hardware issue.
