### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by deb75** [linux-surface/surface-dtx-daemon#3]
Hello,

I had troubles with starting the `surface_dtx` daemon through `systemd`.

The trouble was that `systemd` was launching the service before the `/dev/surface_dtx` device was present. I fixed this by adding one udev rule : 
```
KERNEL=="surface_dtx", TAG+="systemd"
```

and adding the lines : 
```
After=dev-surface_dtx.device
Wants=dev-surface_dtx.device
``` 
in the [Unit] section of `surface-dtx-daemon.service` file.

Just let you know

Regards

**Comment by qzed** [comment]
Thanks! I'll look into it!

**Comment by qzed** [comment]
I've added your solution to the latest release. Thanks again!
